defund12/defund12.org

_emails/austin.md
The email address for Austin council member Ann Kitchen has a typo in it
=> Fix typo in recipient email address (Austin)

_emails/philadelphia.md
bobbyhenon.com is suspended, and I doubt he's still receiving emails there.
=> Add Bobby Henon's phila.gov email

css/main.scss
This PR:
* Changes SCSS variables to [CSS variables](https://caniuse.com/#feat=css-variables)
* Uses the [`prefers-color-scheme` media query](https://caniuse.com/#search=prefers-color-scheme) to change the value of those variables when the browser detects the device uses dark mode
The blue (`#0000ff`) link color is inaccessible on dark backgrounds, so it was changed to the brightest value/saturation in the similar hue group as #0000ff as I deemed reasonable, `#3d81fa`. This color can be changed to something else if it doesn’t fit the intended site aesthetic.
| Light mode (current, default) | Dark mode |
| --- | --- |
| <img width="762" alt="Screen Shot 2020-06-06 at 9 00 42 PM" src="https://user-images.githubusercontent.com/221550/83957783-95052a00-a838-11ea-97ff-cd9093dea6a6.png"> | <img …
=> Add browser-detected darkmode support

_includes/header.html
🌐  Just a tiny lil accessibility win!
> If a page doesn't specify a lang attribute, a screen reader assumes that the page is in the default language that the user chose when setting up the screen reader. If the page isn't actually in the default language, then the screen reader might not announce the page's text correctly. [[source](https://web.dev/html-has-lang/?utm_source=lighthouse&utm_medium=devtools)]
=> Define HTML lang

css/main.scss
I noticed the page shifts horizontally bc there are different lengths of content if you jump between states. Some solutions are summarized here: https://aykevl.nl/2014/09/fix-jumping-scrollbar. 
I went with super light solution for now, before attempting other css tricks. The "downside" is that a scroll bar always appears even when the content is short. But since there are no sub routes, you will always land on the home page, which has enough content to be scrollable and the leftover scrollbar is hardly noticeable.
(chrome)
(chrome)
(chrome)
(safari)
=> make page always scrollable for diff content length across pages

.github/workflows/ci.yml
Alternate approach to https://github.com/defund12/defund12.org/pull/1034, to run the already-Dockerized markdown tests on CI (on every branch) - no worries about python dependencies, etc.
https://github.com/avimoondra/defund12.org/runs/752942165
=> run python tests via docker container

_emails/us/california/albany.md
Closes #629 Should the permalink be albany_ca ? since this is the lesser know Albany? Just a question. I have it as just albany right now because Albany, NY has yet to be added.
=> Add Albany, CA

_emails/us/new_jersey/franklintownship.md
Closes #761 A note on this PR. There is a Franklin, NJ as opposed to a Franklin Township, NJ. Also there are 4 Franklin Townships in NJ.  Source: https://en.wikipedia.org/wiki/Franklin_Township,_New_Jersey
I decided to include the county in the city and title lines because of the potential confusion. Thoughts?
=> Add Franklin Township, Somerset County, NJ

_emails/us/california/sacramento.md
Closes #1247 I also added a comma to this compound sentence because it was necessary. "The current leaders have failed Black and Brown communities many times in the past, and it's time for a change."
=> Remove redundant the & add comma to sacramento

_layouts/email.html
Closes #480.
Needs QA on Android and iOS.
Check any email to see if newlines are respected in the email client (`send email` link).
I set up a [subdomain](https://defund.dionlarson.com/) for QA so you don't need to set up anything locally! ❤️
=> Fix newlines for Android

_layouts/email.html
There were just a few tiny things that could be tweaked when the emails were displayed in HTML.
This is what it looks like afterwards, Chrome on OSX:
=> Tweak email rendering HTML

_emails/us/california/pittsburg.md
Fixes #810 . permalink doesn't need state because the Pennsylvania Pittsburgh is a different spelling.
=> Add Pittsburg, CA

_emails/us/colorado/denver.md
Closes #1360 Adds correct budget numbers for policing and other services.
=> Edit Denver, CO budget numbers to be more accurate

css/main.scss
Looking to make the underline a little more accessible in light and dark desktop modes by creating a new css variable and slightly bumping up the contrast - as opposed to doing anything too radical.
Comparison screenshots below
=> UX anchor link underline color change

.github/workflows/ci.yml
Closes [Add jekyll build to Github actions](https://github.com/defund12/defund12.org/issues/641)
=> build jekyll on non-master branches to confirim build

.github/workflows/ci.yml
see https://stackoverflow.com/questions/61010294/how-to-cache-yarn-packages-in-github-actions, slightly different than https://github.com/actions/cache/blob/master/examples.md#node---yarn bc it doesn't quite work.
Can go even further (caching node_modules), but we can revisit once we pin node version down.
=> cache yarn deps (and combine jest + lint jobs)

src/components/common/Footer.tsx
React has a bug in which `<p>` elements using dangerouslySetInnerHTML are removed at runtime in production build, so we switch those to `<span>`s
=> changed p to span to avert setInnerHTML breaking

_emails/us/new_jersey/new_brunswick.md
I corrected the missing 'g' at the end of gfleming's email address. Looking through the City of New Brunswick's website, I couldn't find anyone that the (bouncing) address smith@cityofnewbrunswick.org could refer to and the mayor's assistant and all city councilors are listed, so I deleted it. Fixes #1536.
=> Corrected New Brunswick emails

.gitignore, _sass/2-layout/_global.scss, package.json, src/DefundUtils.ts, src/own.d.ts, yarn.lock
Related to #1349. Does not fully close because issue cannot be fully addressed without a slight syntax change in email yaml files (see below).
- Adds `remark-breaks` to insert `<br>` on single line breaks (double line breaks creates new `<p>` tags). This helps the formatting of signatures especially when displayed on the website.
- Adds styling for `<ul>` and `<ol>` since lists are sometimes used in emails and get parsed into HTML.
- Adds log files to `.gitignore` since yarn started one for me.
I recommend trying a few emails out, but make sure to take a look at:
- `/anchorage`: list and single line break signatures.
<details>
<summary>Side-by-side screenshot</summary>
<table>
<tr valign="top">
<td><b>New</b><img src="https://user-images.githubusercontent.com/1843883/84835188-07c49100-b001 …
=> Fix email preview (line breaks in signatures and styling for lists)

src/components/email-list/EmailList.tsx
I think due to React Select selectStyles requiring an any type, it always triggers a no-explicit-any warning, so this will simply suppress that warning, since it always shows up and I don't know if it avoidable.
=> Ignore Lint Warning for No Explicit Any

_config.yml, src/components/common/Layout.tsx, src/components/email/Email.tsx, src/types/PropTypes.ts, src/types/SiteConfig.ts
this changes the meta tag to the url from the image generation api: ie. https://defund12-image-api.now.sh/api/preview?city=Sacramento&state=CA
we already hosted the api on vercel serverless, so the api shouldn't have any quotas, and hence, should be quite reliable
replaces #1629
=> Added meta preview image generation using our defund12-image-api
