_emails/cleveland.md

Thank you so much for this resource.

Add Cleveland, OH

---

_emails/dc.md

Washington D.C. ready to merge

added dc.md

---

_emails/cleveland.md

Follow-up to #25 after some proofreading! It’s longer, but clearer ☺️ 
Also includes some contributions from #35 with co-author credit to @jamespeacock (don’t wanna step on toes, just wanted to get these changes up quickly~)

Edit Cleveland, OH letter for easier reading

---

_emails/minneapolis.md

Note: This came almost directly from [this source](https://docs.google.com/spreadsheets/d/1XgCQV5wVHDkBqBEoIFRhVUqBtBrFX3Nbom5C9xZpivg/edit#gid=1054957268).

Add Minneapolis

---

_emails/reno.md

In response to https://github.com/teddywilson/defund12.org/issues/159

Adding Reno, NV

---

_emails/louisville-justice.md
_emails/louisville.md

Add Louisville

---

_emails/dc.md
_emails/philadelphia.md
_emails/sacramento.md
_emails/sandiego.md
_emails/sanfrancisco.md
_emails/sanjose.md

I have updated the missing councilpeople in Philly and added a template for SF!

Philly, San Francisco, Sacramento, San Jose, San Diego (all CA except Philly)

---

_emails/stpaul-schoolboard.md
_emails/stpaul.md

Note: The St. Paul School Board email came almost directly from [this source](https://docs.google.com/spreadsheets/d/1XgCQV5wVHDkBqBEoIFRhVUqBtBrFX3Nbom5C9xZpivg/edit#gid=1054957268).

Add St. Paul School Board & Mayor/City Council

---

_config.yml
_includes/list.html
_layouts/email.html
css/main.scss
js/main.js

links to emails no longer auto-open

---

_emails/buffalo_ny.md

Add Buffalo, NY

---

.gitignore
_emails/seattle.md

Re-merged branch with edits to email.
Relates to issue #188

Add Seattle, WA

---

_emails/houston.md

Update government list to send to all offices and Mayor. Original list is missing 3 members. 
From issue #216

Update Houston to have comprehensive office emails

---

_emails/austin-protests.md

violence police department -> violent police department

fix: typo in austin-protests.md

---

_emails/denver217.md

Added Denver, CO (specifically addresses Senate Bill 217) 

---

_emails/austin-protests.md
_emails/baltimore.md
_emails/elkgrove.md
_emails/fortwayne.md
_emails/grandrapids.md
_emails/oakland.md

I'm sorry if creating a new branch for Oakland is an issue in terms of merging. I know there are multiple edited files here and I'm not very good with Git.. I figured it might be better to start on this one than add endlessly to my other PR. Please let me know if there's a better way in terms of collaboration!

Oakland, CA

---

_emails/newark.md

Based on https://github.com/teddywilson/defund12.org/issues/293
Closes #293

Add Newark, NJ

---

_emails/denver217.md

Fix typo in Denver, CO Senate 217 email

---

_emails/boston.md

typo: boston email to mayor grammar fix

---

_includes/header.html

Better description for screen reader users #332

Add aria-label to 12 = 🚓

---

_includes/header.html

Adds Open Graph tags for a richer content preview on social media. Removes extra character from description meta tag.

Adds Open Graph tags for sharing

---

_includes/list.html

Keyboard nav, proper role, and aria label to span

Add keyboard nav to copyToClipboard span 

---

_emails/la.md

removed non-active councilmember Englander from La.md

---

_layouts/email.html

Allows for keyboard users to tab to anchors. #332

Add hrefs to anchors

---

_emails/la.md

per @robotskirts comment on #48 Mitchell Englander's address has been replaced with John Lee's

update Los Angeles email list

---

_emails/cambridgema.md

changed city attribute from 'Cambridge, MA' to 'Cambridge' to fit with other templates

Updated Cambridge, MA

---

_emails/pueblo.md

The emails sent in looked a little funky, but I cross referenced them with the pueblo.gov website. They are the correct ones listed for city council people.
closes #344

Pueblo, CO

---

_emails/annarbor.md

Ann Arbor, MI

---

_emails/nyc.md

Update NYC to specifically ask for B in cuts

---

_emails/boston-councilors.md

Issue #385 Got consent from issue reporter to just add the ways and means committee email and the city council email to the boston recipients

Add Boston ways and means & city council to recipients

---

_emails/sacramento.md

Fixes #77 Adds more officials to sacramento list. If you just want me to add the recipients and not update the letter I can do that as well.

Update sacramento email list and letter

---

_emails/eureka.md

Add Eureka, CA

---

.gitignore
_emails/membphis.md

Memphis, TN Template

---

_emails/orange_county.md
_emails/orange_county_ca.md

Add Orange County, CA

---

_emails/Nassau.md

Fixes #219 Found her correct email here: http://www.longislandassociation.org/let-your-voice-be-heard

Update Nassau County with correct Denise Ford email

---

_emails/montgomery_county.md
_emails/montgomery_county_md.md

Add Montgomery County, MD

---

_emails/akron.md

Closes https://github.com/teddywilson/defund12.org/issues/304

Add Akron, OH

---

_emails/madison.md

Madison, WI

---

_emails/vallejo.md

Closes https://github.com/teddywilson/defund12.org/issues/318

Add Vallejo, CA

---

_emails/portland_me.md

Portland, ME

---

_emails/tacoma.md

Tacoma, WA

---

pleasanton.md

Pleasanton, CA

---

_emails/lasvegas.md

Las Vegas, NV

---

_emails/wilmington.md

Add Wilmington, DE

---

_emails/westchester.md

adds Westchester County, NY

---

_emails/baltimore_senator.md

Baltimore, MD senator/delegate letter

---

Gemfile
Gemfile.lock
_config.yml

Add sitemap

---

_emails/bakersfield.md

Add Bakersfield, CA

---

_emails/pittsburgh_mayor.md

I saw we have a Pittsburgh template already, but someone made an issue for a mayor-only template that seems very well researched. Not sure what your feelings are about adding more than one template per city but I opened this PR just in case
closes #422

Pittsburgh, PA mayor specific

---

_emails/sanluisobispo.md

San Luis Obispo, CA

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/EMAIL_REQUEST.md

* Doubles down on city-specific messaging
* Hopefully a little clearer and friendlier :)
* Moves the bug report option to the second spot for new issue creation (I think?)

Update new request/triage issue template language

---

_emails/columbiamo.md

Update title for Columbia, MO

---

_emails/fortcollins.md

Fort Collins, CO

---

_emails/berkeley.md

Berkeley, CA

---

_emails/orange_county.md

Fixed incomplete sentence typo in orange_county

---

charlottesville.md

Charlottesville, VA

---

_emails/sacramento.md

Closes https://github.com/defund12/defund12.org/issues/545

Bugfix: Sacramento email list errant characters

---

santacruz.md

Santa Cruz, CA

---

_emails/berkeley.md

Adds email to policy committee to Berkeley, CA

berkeley add policy committee email

---

_emails/chapelhill-active-defund.md

Add Chapel Hill, NC - Actively Defund Template

---

_emails/spokane.md

Spokane, WA

---

_layouts/email.html

https://github.com/defund12/defund12.org/issues/480

Fix issue that newline characters don't work on Android

---

_emails/arlington.md

Arlington va

---

_emails/fairfax.md

Edit Fairfax County, VA body

---

_includes/header.html

Closes #564
I'm no professional, but looking at my local version this seems to work. Someone else should also take a look to verify it'll work on the production first.

Add image previews for specific cities (defund12.org/city) 

---

_emails/santaclaracounty.md

4/4 for issue #449 
closes #449

Santa Clara County, CA

---

_emails/losaltoshills.md

Los Altos Hills, CA

---

_emails/fairfield.md

Add template for Fairfield, CA

---

_emails/mountainview.md

Mountain View, CA

---

_emails/losaltos.md

Los Altos, CA

---

_emails/charlleston_wv.md

I named this with charleston_wv since although there is not yet a charleston.md, Charleston, SC may likely be requested.
This was another govt website with suspicious looking emails for some council members, but they were the only ones available and published
3/4 of #420

Charleston, WV

---

_emails/parkersburg.md

This town has all council members linked through the city clerk so that is the only email I was able to include along with the city development officer. The mayor's email is also unlisted unfortunately
2/4 for #420

Parkersburg, WV

---

_emails/morgantown.md

1/4 for issue #420 
the author sent a WV template which I will edit slightly for each town along with changing the emails of council people obviously
I'll create separate PRs for each though

Morgantown, WV

---

_emails/pleasanton.md

removed defunct nelsonfialho email

---

_emails/richmond.md

Richmond, VA

---

_emails/northampton.md

add Northampton, MA

---

_includes/header.html

Lets us see the custom styling from #573 😍

Bugfix: js file typo

---

_emails/overlandpark.md

Add Overland Park, KS

---

_emails/us/california/losbanos.md

1/2 for issue #659 
ping @shortcircuit3

Update Los Banos, CA per SG

---

_emails/us/california/ripon.md

2/2 for issue #659 
closes #659

Ripon, CA style/grammar

---

_emails/us/california/orange_county.md

update OC for style/grammar

---

_emails/us/california/elkgrove.md

closes #667 
@shortcircuit3 let me know if I shouldn't tag you on these anymore, I know it's a lot!

update Elk Grove, CA for style guide

---

_emails/us/delaware/wilmington.md

Wilmington, DE style/grammar

---

_emails/us/colorado/boulder.md

Boulder, CO style/content updates

---

_emails/us/colorado/pueblo.md

Update Pueblo, CO for style/grammar

---

_emails/us/colorado/fortcollins.md

Fort Collins, CO for style/grammar

---

_emails/us/delaware/wilmington.md

update Wilmington, DE for style/grammar

---

_config.yml
_includes/list.html

Add contact email to footer

---

_emails/us/florida/orlando.md

updating Orlando, FL for style/grammar

---

_emails/us/california/santa-barbara.md

Fixes #675. I _think_ I also correctly cleaned up a few other formatting issues.

Edit Santa Barbara: update housing allocation, formatting fixes

---

_emails/us/massachusetts/boston.md

closes: https://github.com/defund12/defund12.org/issues/751

Redirect /cambridgema -> /cambridge

---

_emails/us/california/santacruz.md

Remove typo in Santa Cruz letter

---

_emails/us/colorado/boulder.md

Fixes #787 
Removes old, inaccurate data from the last paragraph, and incorporates the asks at the end of that last paragraph into the first. Add blurb about Minneapolis city council pledging to defund.

Remove invalid boulder data

---

_emails/miami.md

add Miami, FL

---

_emails/us/maryland/montgomery_county.md

Closes #759 . Capitalizes Black in all instances. black is a color. Black refers to people.

Capitalize Black in Montogomery County, MD email

---

_emails/sanantonio.md

Add San Antonio, TX

---

_emails/glendale.md

add glendale, CA

---

_emails/us/new_jersey/newark.md

Closes #684. That issue said that the first paragraph of the email makes reference to some of the demands from 8cantwait.org. These demands are actually at odds with the more critical demand to defund the police.

Edit sentence in newark letter

---

_emails/tempe.md

add tempe, AZ

---

EMAIL_TEMPLATE_STYLE_GUIDE.md

Also includes examples from other sources and some formatting updates

add locale-specific and misc suggestions in style guide

---

EMAIL_TEMPLATE_STYLE_GUIDE.md

fix line break

---

_emails/us/california/unioncity.md

Add Union City, CA

---

_emails/us/alabama/birmingham.md

Add Birmingham [Vote is Tomorrow!]

---

.github/ISSUE_TEMPLATE/EMAIL_REQUEST.md
TEAMS.md

A few misc. changes regarding email requests and team copy

Internal workflow copy improvements

---

_emails/us/louisiana/neworleans.md

Added New Orleans

---

_emails/us/california/hayward.md

Add Hayward, CA

---

_emails/us/oklahoma/norman.md

added Norman, Oklahoma

---

_emails/us/california/fullerton.md

added Fullerton, California

---

_emails/us/california/lacounty.md

Add LA County, CA

---

_emails/us/rhode_island/cranston.md

Add Cranston, RI

---

_emails/us/virginia/fairfax.md

On https://defund12.org/fairfax:
I think the proposed edit should handle the newlines correctly.

Update fairfax.md to handle newlines correctly

---

_emails/us/california/sanfrancisco.md

addresses edit request in #105

added Board of Education emails

---

_emails/us/rhode_island/pawtucket.md

Add Pawtucket, RI

---

_emails/us/california/riverside_county.md

add Riverside, CA

---

_emails/us/colorado/aurora.md

add Aurora, CA

---

_emails/us/north_carolina/greensboro.md

Add Greensboro, NC

---

_emails/us/california/menlopark.md

add Menlo Park, CA

---

_emails/us/michigan/southfield.md

Add Southfield, MI

---

_emails/us/california/belmont.md

Add Belmont, CA

---

_emails/us/california/ventura.md

add Ventura, CA

---

_emails/us/maryland/frederickcounty.md

Add Frederick County, MD

---

_emails/us/new_jersey/jersey-city.md

Add email template: Jersey City, NJ

---

_emails/us/kansas/kansascityMO.md

edit Kansas City, MO intro graf

---

_emails/us/california/hayward.md

Hayward CA: Fix misspellings in emails

---

_emails/us/tennesee/clarksville.md

Add email template: Clarksville, TN

---

_emails/us/illinois/chicago.md

Update Chicago emails, add linebreaks to signature

---

_emails/us/washington_dc/dc.md

Remove wrong & keep correct address for DC Councilor Bonds

---

_emails/us/kentucky/louisville-justice.md

edit Louisville, KY letter per style guide

---

_emails/us/california/santa-monica.md

Add email template: Santa Monica, CA

---

_emails/somerville.md

Add Somerville, MA

---

.github/ISSUE_TEMPLATE/TRIAGE_ACCESS.md

remove incorrect admin assignee

Correct triage access issue template assignees

---

_emails/us/nevada/lasvegas.md

Closes #968 . Adds education to the list of things they could spend the money on instead. I did not include changes to the ending of the email like the reporter suggested. Doing so would not be aligned with the style guide.

Edit Las Vegas, NV to include ask for education

---

_emails/eauclaire.md

Add Eau Claire, WI

---

_emails/us/oregon/eugene.md

Closes #799.
Tests at:
https://github.com/dionlarson/defund12.org/actions/runs/130103061

Add Eugene, OR

---

_emails/us/virginia/alexandria.md

Closes #971.
Tests at:
https://github.com/dionlarson/defund12.org/actions/runs/130103466

Add Alexandria, VA

---

_emails/us/florida/stpetersburg.md

Closes #639.
Tests at:
https://github.com/dionlarson/defund12.org/runs/755010573

Add St Petersburg, FL

---

_emails/us/florida/tampa.md

Closes #652.
Tests at:
https://github.com/dionlarson/defund12.org/runs/755011739

Add Tampa, FL

---

_emails/us/kentucky/lexington.md

Add Lexington, KY

---

_emails/us/ohio/toledo.md

add Toledo, OH email

---

_emails/us/arizona/tuscon.md

Add Tucson, AZ

---

_emails/us/california/petaluma.md

add Petaluma, CA

---

_emails/us/rhode_island/jamestown.md

add Jamestown, RI

---

_emails/us/massachusetts/arlington.md

add Arlington, MA

---

_emails/us/north_carolina/winstonsalem.md

add Winston-Salem, NC

---

_emails/us/california/stockton.md

add Stockton, CA

---

EMAIL_TEMPLATE_STYLE_GUIDE.md

Update style guide

---

.github/workflows/ci.yml

syntax error! Also up to date with cache, v2

speed up build time w/bundler gem caching (v2)

---

_emails/us/virginia/williamsburg.md

Replaces: https://github.com/defund12/defund12.org/pull/1049
@wendywx

Add Williamsburg, VA

---

_emails/us/tennesee/knoxville.md

replaces https://github.com/defund12/defund12.org/pull/1105
Closes #709 & Closes #1107 bug

Add Knoxville, TN

---

_emails/us/michigan/royaloak.md

Closes #612 . Addresses the concerns in this PR comments #1077

Add Royal Oak, MI

---

_emails/us/texas/fortworth.md

Add Fort Worth, TX

---

_emails/us/california/pasadena.md

Add Pasadena, CA

---

_emails/us/california/sanleandro.md

San leandro

---

_emails/us/texas/irving.md

Add Irving, TX

---

_emails/us/california/dalycity.md

Closes #644, also a reopening of #1092

Add Daly City, CA

---

_emails/us/massachusetts/newton.md

Add Newton, MA

---

_emails/us/new_hampshire/concord.md

Add Concord, NH

---

_emails/us/nebraska/omaha.md

Added Omaha, Nebraska template

---

_emails/us/delaware/newark.md

Add Newark, DE

---

_emails/us/michigan/eastlansing.md

Add East Lansing, MI

---

_emails/us/wisconsin/lacrosse.md

Closes #701 . I also added the mayor's email because it was missing from the original email. `kabatt@cityoflacrosse.org`

Add La Crosse, WI

---

_emails/us/arkansas/littlerock.md

Add Little Rock, AR

---

_emails/us/vermont/burlington.md

Add Burlington, VT

---

_emails/us/california/torrance.md

Add Torrance, CA

---

_emails/us/california/lafayette.md

Add Lafayette, CA

---

_emails/us/new_york/rochester.md

Add Rochester, NY

---

_emails/us/connecticut/newhaven.md

Add New Haven, CT

---

_emails/us/virginia/norfolk.md

add letter for Norfolk, VA

---

_emails/us/california/hollister.md

Add Hollister, CA

---

_emails/us/louisiana/batonrouge.md

Add Baton Rouge, LA

---

_emails/us/massachusetts/worcester.md

Add Worcester, MA

---

_emails/us/california/salinas.md

Add Salinas, CA

---

_emails/us/florida/jacksonville.md

Closes #504. I personally like the edited down version. It's still long, but it does work. 
(no longer running into #893)

Add Jacksonville, FL

---

_emails/us/florida/gainesville.md

Add Gainesville, FL

---

_emails/us/south_carolina/charleston.md

Closes #792 
Added -sc to permalink to prevent confusion with charleston, wv letter

Add Charleston, SC

---

_emails/us/georgia/athens.md

Add Athens, GA

---

_emails/us/ohio/cincinnati.md

Add Cincinnati, OH

---

_emails/us/arizona/phoenix.md

I did not change content of letter. I think it's important to at least get this change up while waiting for a better rewrite.
Related to #669 but does not fully address.

Fix formatting on Phoenix

---

_emails/us/new_york/beacon.md

Added Beacon, NY

---

_emails/us/pennsylvania/statecollege.md

Recreates PR [#1006](https://github.com/defund12/defund12.org/pull/1006)
Adds council members direct emails.
Issue #1008

Recreates State College

---

_emails/us/california/scottsvalley.md

Added scottsvalley.md from CLI

---

_emails/us/vermont/burlington-mayor.md

add second letter for Burlington, VT

---

_emails/us/new_mexico/santafe.md

add new letter for Santa Fe, NM

---

_emails/us/florida/palmbeachcounty.md

add letter for Palm Beach County, FL

---

_emails/us/california/southsanfrancisco.md

Add South San Francisco, CA

---

_emails/us/illinois/oakpark.md

Add Oak Park, IL

---

_emails/us/arizona/bentoncounty.md

Add Benton County, AR

---

_emails/us/virginia/fairfax.md

Closes #1223 Remove incorrect providence district email and provide correct one per issue

Edit Fairfax, VA recipient list

---

_emails/us/michigan/lansing.md

Add Lansing, MI

---

_emails/us/maryland/baltimorecounty.md

Add Baltimore County, MD

---

_emails/us/virginia/loudouncounty.md

Add Loudoun County, VA

---

_emails/us/nebraska/lincoln.md

Add Lincoln, NE

---

_emails/us/washington_state/olympia.md

add Olympia, WA

---

_emails/us/california/westcovina.md

add West Covina, CA

---

_emails/us/california/nevada_county.md

add Nevada County, CA

---

_emails/us/california/fresno.md

Add Fresno, CA

---

_emails/us/maryland/princegeorges.md

add Prince George's County, MD

---

_emails/us/florida/gainesville.md

Fixes email address in Gainesville template

---

_emails/us/virginia/princewilliamcounty.md

Add Prince William County, VA

---

_emails/us/ohio/dayton.md

Add Dayton, OH

---

_emails/us/oregon/yamhillcounty.md

Add Yamhill County, OR

---

_emails/us/ohio/mcminnville.md

Add McMinnville, OH

---

_emails/us/california/elcerrito.md

add El Cerrito, CA letter

---

_emails/us/new_jersey/englewood.md

Add Englewood, NJ

---

_emails/us/louisiana/jeffersonparish.md

Add Jefferson Parish, LA

---

_emails/us/colorado/westminster.md

Add Westminster, CO

---

_emails/us/virginia/roanokecounty.md

Add Roanoke County, VA

---

_emails/us/california/anaheim.md

Add Anaheim, CA

---

_emails/us/alabama/huntsville.md

Update letter for Huntsville, AL

---

_emails/us/california/claremont.md

Add Claremont, CA

---

_emails/us/california/lahabra.md

Added La Habra, CA

---

_emails/us/maryland/annapolis.md

Add Annapolis, MD

---

_emails/us/new_jersey/newbrunswick.md

Add New Brunswick, NJ

---

_emails/us/california/upland.md

Add Upland, CA

---

_emails/us/montana/bozeman.md

Add Bozeman, MT

---

_emails/us/california/sangabriel.md

Add San Gabriel, CA

---

_emails/us/idaho/boise.md

update non-bouncing emails for Boise, ID

---

README.md
_config.yml

Change racial inequality to racial injustice

---

_emails/us/michigan/detroit.md

add Detroit, MI

---

_emails/us/virginia/winchester.md

add Winchester, VA

---

_emails/us/pennsylvania/lancaster.md

add Lancaster, PA

---

_emails/us/new_mexico/las_cruces.md

add Las Cruces, NM

---

_emails/us/california/merced.md

add Merced, CA

---

_emails/us/california/walnut_creek.md

Add Walnut Creek, CA

---

_emails/us/north_carolina/wake_county.md

Closes #1412 to address County officials instead of the Mayor

Fix typo in Wake County, NC letter

---

.github/workflows/ci.yml
test/main.test.js

send failure messages to #deploys and #general

---

_emails/us/california/santa_clara.md

Add letter for Santa Clara, CA (city)

---

_emails/us/new_york/canandaigua.md

add new letter for Canandaiugua, NY

---

_emails/us/alaska/anchorage.md

Add Anchorage, AK

---

_emails/us/louisiana/shreveport.md

Add Shreveport, LA

---

_emails/us/california/mill_valley.md

add new letter for Mill Valley, CA

---

_emails/us/washington_state/kennewick.md

Add Kennewick, WA

---

_emails/us/washington_state/richland.md

Add Richland, WA

---

_emails/us/illinois/evanston.md

Add Evanston, IL

---

_emails/us/oregon/washington_county.md

closes #1141 
replace #1415 (messed up the merge)
fixes permalink issue

Add Washington County, OR

---

_config.yml
_includes/list.html
css/main.scss

This reverts commit f94771e76db7edb297ab8e4e139bb4d65e5ea834.

Revert "Added sticky footer (#1442)"

---

css/main.scss

resolves #1437 
simply added margin of 16px to top and bottom of links for mobile devices

Margin between links

---

EMAIL_TEMPLATE_STYLE_GUIDE.md

discourage demand lists, info for organizers, caution about city vs. county

Style guide updates: discourage demand lists

---

_emails/us/california/burbank.md

Burbank, CA (/burbank)

---

_emails/us/north_carolina/alamance.md

Alamance, NC (/alamance)

---

_emails/us/colorado/durango.md

Durango, CO (/durango)

---

_emails/us/georgia/johnscreek.md

Johns Creek, GA (/johnscreek)

---

_emails/us/california/oakland.md

Hey all,
Heard from APTP (local organization who helped draft the original email) that they wanted point 3 removed, as it opened up some legal liability for them.
Submitting a request to delete that bullet point.
Thanks!

Updating oakland wording

---

_emails/us/california/los_gatos.md

Los Gatos, CA (/losgatos)

---

_emails/us/california/san_bernardino_county.md

San Bernardino County, CA (/sanbernardinocounty)

---

_emails/us/vermont/middlebury.md

Middlebury, VT (/middlebury)

---

_emails/us/florida/lakeland.md

Lakeland, FL (/lakeland)

---

_emails/us/california/monterey.md

add new letter for Monterey, CA

---

_emails/us/california/newark.md

Newark, CA (/newark-ca)

---

_emails/us/california/pomona.md

Pomona, CA (/pomona)

---

_emails/us/new_york/ithaca.md

Ithaca, NY (/ithaca)

---

_emails/us/virginia/blacksburg.md

Blacksburg, VA (/blacksburg)

---

_emails/us/massachusetts/pittsfield.md

Pittsfield, MA (/pittsfield)

---

_emails/us/california/sanbruno.md

add San Bruno, CA

---

_sass/2-layout/_list.scss

style react-select to fix width

---

_emails/us/alabama/mobile.md

Mobile, AL (/mobile)

---

_emails/us/illinois/peoria.md

Peoria, IL (/peoria)

---

_emails/us/virginia/roanoke.md

Roanoke, VA (/roanoke)

---

_emails/us/virginia/salem.md

Salem, VA (/salem)

---

_emails/us/massachusetts/natick.md

Natick, MA (/natick)

---

_emails/us/iowa/davenport.md

Davenport, IA (/davenport)

---

_emails/us/california/millbrae.md

Millbrae, CA (/millbrae)

---

_emails/us/texas/el_paso.md

El Paso, TX (/elpaso)

---

_emails/us/california/cupertino.md

Cupertino, CA (/cupertino)

---

_emails/us/washington_state/walla_walla.md

Walla Walla, WA (/wallawalla)

---

_emails/us/washington_state/lakewood.md

Lakewood, WA (/lakewood)

---

_emails/us/iowa/cedar_rapids.md

Cedar Rapids, IA (/cedar-rapids)

---

_emails/us/california/artesia.md

Artesia, CA (/artesia)

---

_emails/us/new_jersey/bergen_county.md

Bergen County, NJ (/bergencounty)

---

_emails/us/alaska/juneau.md

Juneau, AK (/juneau)

---

_emails/us/maryland/st_marys_county.md

St. Mary's County, MD (/stmarys)

---

_emails/us/north_carolina/wilmington.md

Closes #1064 . Added -nc to permalink because a Wilmington, DE already exists

Add Wilmington, NC

---

_config.yml
src/components/common/Header.tsx
src/components/common/Layout.tsx
src/components/email/Email.tsx
src/pages/404.tsx
src/pages/index.tsx
src/types/PropTypes.ts
src/types/SiteConfig.ts

Improve social previews metadata in React

---

_emails/us/new_jersey/middlesex_county.md

Middlesex County, NJ (/middlesexcounty)

---

_emails/us/maryland/howard_county_.md

Howard County , MD (/howardcounty)

---

_emails/us/virginia/henrico_county.md

Henrico County, VA (/henrico-county)

---

_emails/us/new_york/dutchess_county.md

Dutchess County, NY (/dutchesscounty)

---

README.md

Added both Windows and plain bash install instructions for nvm

updated nvm install instructions

---

_emails/us/california/victorville.md

Victorville, CA (/victorville)

---

_emails/us/massachusetts/springfield.md

Added Springfield

---

_emails/us/california/san_mateo_county.md

Add San Mateo County, CA

---

_emails/us/south_carolina/columbia.md

Columbia, SC (/columbia)

---

_emails/us/california/arroyo_grande.md

Arroyo Grande, CA (/arroyo-grande)

---

_emails/us/california/san_luis_obispo_county.md

San Luis Obispo County, CA (/san-luis-obispo-county)

---

_emails/us/tennesee/chattanooga.md

Chattanooga, TN (/chattanooga)

---

_emails/us/california/concord.md

Concord, CA (/concord)

---

_emails/us/massachusetts/malden.md

Malden, MA (/malden)

---

_emails/us/new_york/syracuse.md

Syracuse, NY (/syracuse)

---

EMAIL_TEMPLATE_STYLE_GUIDE.md
TEAMS.md

* Make sure docs links use `master` branch instead of `gh-pages` branch
* Minor formatting/language nitty edits

Docs: correct links and adjust formatting

---

src/components/email-list/EmailList.tsx

sort list of cities before grouping into states

---

_emails/us/massachusetts/billerica.md

Billerica, MA (/billerica)

---

_emails/us/illinois/peoria.md

Updated Peoria, IL (/peoria)

---

_emails/README.md
src/components/email/Email.tsx

Revival of https://github.com/defund12/defund12.org/pull/832
Closes https://github.com/defund12/defund12.org/issues/640

Stop using to: and use bcc:

---

package.json
yarn.lock

this is what it looks like when I try to commit bad code:

Lint typescript on commit

---

_emails/us/oregon/beaverton.md

Beaverton, OR (/beaverton)

---

_emails/us/colorado/jefferson_county.md

Jefferson County, CO (/jeffersoncounty)

---

_emails/us/arkansas/springdale.md

Springdale, AR (/springdale)

---

_emails/us/virginia/lynchburg.md

Lynchburg, VA (/lynchburg)

---

_emails/us/michigan/novi.md

Novi, MI (/novi)

---

_emails/us/north_carolina/fayetteville.md

Fayetteville, NC (/fayetteville)

---

_emails/us/illinois/belleville.md

Belleville, IL (/belleville)

---

_emails/us/tennesee/murfreesboro.md

Murfreesboro, TN (/murfreesboro)

---

_emails/us/ohio/oxford.md

Oxford, OH (/oxford)

---

_emails/us/california/vallejo.md

Update vallejo ca (/vallejo-ca)

---

_emails/us/massachusetts/worcester.md

update Worcester, MA (/worcester)

---

_emails/us/california/patterson.md

Patterson, CA (/patterson)

---

_emails/us/california/ceres.md

Ceres, CA (/ceres)

---

_emails/us/massachusetts/brookline.md

Brookline, MA (/brookline)

---

_emails/us/california/victorville.md

edit Victorville, CA (/victorville)

---

_emails/us/pennsylvania/whitpain_township.md

Whitpain Township, PA (/whitpain)

---

_emails/us/virginia/hampton.md

Added Hampton, VA

---

_emails/us/california/fairfax.md

Fairfax, CA (/fairfax-ca)

---

_emails/us/california/riverbank.md

Riverbank, CA (/riverbank)

---

_emails/us/florida/boca_raton.md

Boca Raton, FL (/bocaraton)

---

_emails/us/california/contra_costa_county.md

Contra Costa County, CA (/contracosta)

---

_emails/us/kansas/topeka.md

Topeka, KS (/topeka)

---

_emails/us/new_hampshire/dover.md

Dover, NH (/dover-nh)

---

_emails/us/louisiana/lafayette.md

Lafayette, LA (/lafayette-la)

---

_emails/us/wyoming/teton_county.md

Teton County, WY (/teton-county)

---

_emails/us/connecticut/stamford.md

Added Stamford, CT

---

_emails/us/california/thousand_oaks.md

Added Thousand Oaks, CA

---

_emails/us/florida/collier_county.md

Collier County, FL (/colliercounty)

---

_emails/us/new_jersey/clifton.md

Clifton, NJ (/clifton)

---

_emails/us/florida/broward_county.md

Broward County, FL (/browardcounty)

---

_emails/us/california/corona.md

Corona, CA (/corona)

---

_emails/us/california/palmdale.md

Palmdale, CA (/palmdale)

---

_emails/us/new_mexico/truth_or_consequences.md

Truth or Consequences, NM (/truthorconsequences)

---

_emails/us/new_jersey/trenton.md

Trenton, NJ (/trenton)

---

_emails/us/virginia/montgomery_county.md

Montgomery County, VA (/montgomerycounty)

---

_emails/us/texas/plano.md

Plano, TX (/plano)

---

_emails/us/arizona/scottsdale.md

Scottsdale, AZ (/scottsdale)

---

_emails/us/california/brentwood.md

Added Brentwood, CA (/brentwood)

---

_emails/us/california/tiburon.md

Add Tiburon, CA (/tiburon)

---

_emails/us/florida/fort_lauderdale.md

Fort Lauderdale, FL (/fortlauderdale)

---

_emails/us/maryland/university_of_maryland.md

University of Maryland (/umd)

---

_emails/us/new_york/schenectady.md

Add Schenectady, NY (/schenectady)

---

_emails/us/washington_state/puyallup.md

Add Puyallup, WA (/puyallup)

---

_emails/us/washington_state/kirkland.md

Add Kirkland, WA (/kirkland)

---

_emails/us/washington_state/lynnwood.md

Add Lynnwood, WA (/lynnwood)

---

_emails/us/washington_state/bonney_lake.md

Add Bonney Lake, WA (/bonneylake)

---

_emails/us/washington_state/covington.md

Add Covington, WA (/covington)

---

_emails/us/connecticut/ridgefield.md

Add Ridgefield, CT (/ridgefield)

---

_emails/us/oregon/salem.md

Add Salem, OR (/salem-or)

---

_emails/us/pennsylvania/edgewood_borough.md

Add Edgewood Borough, PA (/edgewood-borough)

---

_emails/us/maryland/anne_arundel_county.md

Add Anne Arundel County, MD (/anne-arundel)

---

_emails/us/illinois/elgin.md

Add Elgin, IL (/elgin)

---

_emails/us/new_jersey/morristown.md

Add Morristown, NJ (/morristown)

---

_emails/us/florida/brevard_county.md

Brevard County, FL (/brevardcounty)

---

_emails/us/alabama/decatur.md

Decatur, AL (/decatur-al)

---

_emails/us/illinois/elmhurst.md

Add Elmhurst, IL (/elmhurst)

---

_emails/us/washington_state/bellingham.md

Add Bellingham, WA (/bellingham)

---

_emails/us/california/yolo_county.md

Add Yolo County, CA (/yolo-county)

---

_emails/us/colorado/avon.md

Avon, CO (/avon)

---

_emails/us/florida/kissimmee.md

Kissimmee, FL (/kissimmee)

---

_emails/us/pennsylvania/hummelstown.md

Hummelstown, PA (/hummelstown)

---

_emails/us/california/davis.md

Add Davis, CA (/davis)

---

_emails/us/virginia/frederick_county.md

Add Frederick County, VA (/frederick-county)

---

_emails/us/florida/melbourne.md

Add Melbourne, FL (/melbourne)

---

_emails/us/illinois/cook_county.md

Cook County, IL (/cookcounty)

---

_emails/us/florida/orange_county.md

Orange County, FL (/orange-county-fl)
